<template>
  <div>
    <form-builder v-model="form"></form-builder>
  </div>
</template>

<script>
import FormBuilder from "../../components/organisms/FormBuilder.vue";
export default {
  components: {
    FormBuilder,
  },
  data() {
    return {
      form: {
        components: [
          {
            title: "Panel",
            labelWidth: "",
            labelMargin: "",
            theme: "default",
            tooltip: "",
            customClass: "",
            collapsible: false,
            hidden: false,
            hideLabel: false,
            disabled: false,
            modalEdit: false,
            key: "panel",
            tags: [],
            properties: {},
            customConditional: "",
            conditional: { json: "", show: null, when: null, eq: "" },
            logic: [],
            attributes: {},
            overlay: {
              style: "",
              page: "",
              left: "",
              top: "",
              width: "",
              height: "",
            },
            type: "panel",
            label: "Panel",
            breadcrumb: "default",
            tabindex: "",
            input: false,
            placeholder: "",
            prefix: "",
            suffix: "",
            multiple: false,
            defaultValue: null,
            protected: false,
            unique: false,
            persistent: false,
            clearOnHide: false,
            refreshOn: "",
            redrawOn: "",
            tableView: false,
            dataGridLabel: false,
            labelPosition: "top",
            description: "",
            errorLabel: "",
            autofocus: false,
            dbIndex: false,
            customDefaultValue: "",
            calculateValue: "",
            calculateServer: false,
            widget: null,
            validateOn: "change",
            validate: {
              required: false,
              custom: "",
              customPrivate: false,
              strictDateValidation: false,
              multiple: false,
              unique: false,
            },
            allowCalculateOverride: false,
            encrypted: false,
            showCharCount: false,
            showWordCount: false,
            allowMultipleMasks: false,
            addons: [],
            tree: false,
            lazyLoad: false,
            components: [
              {
                label: "Name",
                labelPosition: "top",
                labelWidth: "",
                labelMargin: "",
                placeholder: "",
                description: "",
                tooltip: "",
                prefix: "",
                suffix: "",
                widget: { type: "input" },
                inputMask: "",
                displayMask: "",
                allowMultipleMasks: false,
                customClass: "",
                tabindex: "",
                autocomplete: "",
                hidden: false,
                hideLabel: false,
                showWordCount: false,
                showCharCount: false,
                mask: false,
                autofocus: false,
                spellcheck: true,
                disabled: false,
                tableView: true,
                modalEdit: false,
                multiple: false,
                persistent: true,
                inputFormat: "plain",
                protected: false,
                dbIndex: false,
                case: "",
                truncateMultipleSpaces: false,
                encrypted: false,
                redrawOn: "",
                clearOnHide: true,
                customDefaultValue: "",
                calculateValue: "",
                calculateServer: false,
                allowCalculateOverride: false,
                validateOn: "change",
                validate: {
                  required: false,
                  minLength: "",
                  maxLength: "",
                  minWords: "",
                  maxWords: "",
                  pattern: "",
                  customMessage: "",
                  custom: "",
                  customPrivate: false,
                  json: "",
                  strictDateValidation: false,
                  multiple: false,
                  unique: false,
                },
                unique: false,
                errorLabel: "",
                errors: "",
                key: "name",
                tags: [],
                properties: {},
                conditional: { show: null, when: null, eq: "", json: "" },
                customConditional: "",
                logic: [],
                attributes: {},
                overlay: {
                  style: "",
                  page: "",
                  left: "",
                  top: "",
                  width: "",
                  height: "",
                },
                type: "textfield",
                input: true,
                refreshOn: "",
                dataGridLabel: false,
                addons: [],
                inputType: "text",
                id: "erd1x3o",
                defaultValue: "",
              },
              {
                label: "Icon",
                labelPosition: "top",
                labelWidth: "",
                labelMargin: "",
                placeholder: "",
                description: "",
                tooltip: "",
                prefix: "",
                suffix: "",
                widget: { type: "input" },
                inputMask: "",
                displayMask: "",
                allowMultipleMasks: false,
                customClass: "",
                tabindex: "",
                autocomplete: "",
                hidden: false,
                hideLabel: false,
                showWordCount: false,
                showCharCount: false,
                mask: false,
                autofocus: false,
                spellcheck: true,
                disabled: false,
                tableView: true,
                modalEdit: false,
                multiple: false,
                persistent: true,
                inputFormat: "plain",
                protected: false,
                dbIndex: false,
                case: "",
                truncateMultipleSpaces: false,
                encrypted: false,
                redrawOn: "",
                clearOnHide: true,
                customDefaultValue: "",
                calculateValue: "",
                calculateServer: false,
                allowCalculateOverride: false,
                validateOn: "change",
                validate: {
                  required: false,
                  minLength: "",
                  maxLength: "",
                  minWords: "",
                  maxWords: "",
                  pattern: "",
                  customMessage: "",
                  custom: "",
                  customPrivate: false,
                  json: "",
                  strictDateValidation: false,
                  multiple: false,
                  unique: false,
                },
                unique: false,
                errorLabel: "",
                errors: "",
                key: "icon",
                tags: [],
                properties: {},
                conditional: { show: null, when: null, eq: "", json: "" },
                customConditional: "",
                logic: [],
                attributes: {},
                overlay: {
                  style: "",
                  page: "",
                  left: "",
                  top: "",
                  width: "",
                  height: "",
                },
                type: "textfield",
                input: true,
                refreshOn: "",
                dataGridLabel: false,
                addons: [],
                inputType: "text",
                id: "eg4y7wa",
                defaultValue: "",
              },
              {
                label: "Url",
                labelPosition: "top",
                labelWidth: "",
                labelMargin: "",
                placeholder: "",
                description: "",
                tooltip: "",
                prefix: "",
                suffix: "",
                widget: { type: "input" },
                inputMask: "",
                displayMask: "",
                allowMultipleMasks: false,
                customClass: "",
                tabindex: "",
                autocomplete: "",
                hidden: false,
                hideLabel: false,
                showWordCount: false,
                showCharCount: false,
                mask: false,
                autofocus: false,
                spellcheck: true,
                disabled: false,
                tableView: true,
                modalEdit: false,
                multiple: false,
                persistent: true,
                inputFormat: "plain",
                protected: false,
                dbIndex: false,
                case: "",
                truncateMultipleSpaces: false,
                encrypted: false,
                redrawOn: "",
                clearOnHide: true,
                customDefaultValue: "",
                calculateValue: "",
                calculateServer: false,
                allowCalculateOverride: false,
                validateOn: "change",
                validate: {
                  required: false,
                  minLength: "",
                  maxLength: "",
                  minWords: "",
                  maxWords: "",
                  pattern: "",
                  customMessage: "",
                  custom: "",
                  customPrivate: false,
                  json: "",
                  strictDateValidation: false,
                  multiple: false,
                  unique: false,
                },
                unique: false,
                errorLabel: "",
                errors: "",
                key: "url",
                tags: [],
                properties: {},
                conditional: { show: null, when: null, eq: "", json: "" },
                customConditional: "",
                logic: [],
                attributes: {},
                overlay: {
                  style: "",
                  page: "",
                  left: "",
                  top: "",
                  width: "",
                  height: "",
                },
                type: "textfield",
                input: true,
                refreshOn: "",
                dataGridLabel: false,
                addons: [],
                inputType: "text",
                id: "exy950m",
                defaultValue: "",
              },
              {
                label: "Schema",
                labelPosition: "top",
                labelWidth: "",
                labelMargin: "",
                description: "",
                tooltip: "",
                customClass: "",
                tabindex: "",
                openWhenEmpty: false,
                disableAddingRemovingRows: false,
                conditionalAddButton: "",
                hidden: false,
                hideLabel: false,
                autofocus: false,
                disabled: false,
                tableView: false,
                modalEdit: false,
                templates: {
                  header:
                    '<div class="row">\n      {% util.eachComponent(components, function(component) { %}\n        {% if (displayValue(component)) { %}\n          <div class="col-sm-2">{{ t(component.label) }}</div>\n        {% } %}\n      {% }) %}\n    </div>',
                  tableHeader:
                    '\n      <tr>\n        {% util.eachComponent(components, function(component) { %}\n          {% if (!component.hasOwnProperty(\'tableView\') || component.tableView) { %}\n            <td class="editgrid-table-column">{{ component.label }}</td>\n          {% } %}\n        {% }) %}\n        {% if (!instance.options.readOnly && !instance.disabled) { %}\n          <td class="editgrid-table-column">Actions</td>\n        {% } %}\n      </tr>\n    ',
                  row: '<div class="row">\n      {% util.eachComponent(components, function(component) { %}\n        {% if (displayValue(component)) { %}\n          <div class="col-sm-2">\n            {{ isVisibleInRow(component) ? getView(component, row[component.key]) : \'\'}}\n          </div>\n        {% } %}\n      {% }) %}\n      {% if (!instance.options.readOnly && !instance.disabled) { %}\n        <div class="col-sm-2">\n          <div class="btn-group pull-right">\n            <button class="btn btn-default btn-light btn-sm editRow"><i class="{{ iconClass(\'edit\') }}"></i></button>\n            {% if (!instance.hasRemoveButtons || instance.hasRemoveButtons()) { %}\n              <button class="btn btn-danger btn-sm removeRow"><i class="{{ iconClass(\'trash\') }}"></i></button>\n            {% } %}\n          </div>\n        </div>\n      {% } %}\n    </div>',
                  tableRow:
                    '\n      {% util.eachComponent(components, function(component) { %}\n          {% if (!component.hasOwnProperty(\'tableView\') || component.tableView) { %}\n            <td class="editgrid-table-column">\n              {{ getView(component, row[component.key]) }}\n            </td>\n          {% } %}\n        {% }) %}\n        {% if (!instance.options.readOnly && !instance.disabled) { %}\n          <td class="editgrid-table-column">\n            <div class="btn-group">\n              <button class="btn btn-default btn-light btn-sm editRow" aria-label="{{ t(\'Edit row\') }}"><i class="{{ iconClass(\'edit\') }}"></i></button>\n              {% if (!instance.hasRemoveButtons || instance.hasRemoveButtons()) { %}\n              <button class="btn btn-danger btn-sm removeRow" aria-label="{{ t(\'Remove row\') }}"><i class="{{ iconClass(\'trash\') }}"></i></button>\n              {% } %}\n            </div>\n          </td>\n        {% } %}\n    ',
                  footer: "",
                },
                rowClass: "",
                addAnother: "",
                modal: false,
                saveRow: "",
                removeRow: "Cancel",
                persistent: true,
                inlineEdit: false,
                protected: false,
                dbIndex: false,
                encrypted: false,
                redrawOn: "",
                clearOnHide: true,
                customDefaultValue: "",
                calculateValue: "",
                calculateServer: false,
                allowCalculateOverride: false,
                validateOn: "change",
                validate: {
                  required: false,
                  minLength: "",
                  maxLength: "",
                  customMessage: "",
                  custom: "",
                  customPrivate: false,
                  json: "",
                  strictDateValidation: false,
                  multiple: false,
                  unique: false,
                },
                rowDrafts: false,
                errorLabel: "",
                errors: "",
                key: "schema",
                tags: [],
                properties: {},
                conditional: { show: null, when: null, eq: "", json: "" },
                customConditional: "",
                logic: [],
                attributes: {},
                overlay: {
                  style: "",
                  page: "",
                  left: "",
                  top: "",
                  width: "",
                  height: "",
                },
                type: "editgrid",
                displayAsTable: false,
                input: true,
                components: [
                  {
                    collapsible: false,
                    key: "panel1",
                    type: "panel",
                    label: "Panel",
                    input: false,
                    tableView: false,
                    components: [
                      {
                        label: "Name",
                        tableView: true,
                        key: "name",
                        type: "textfield",
                        input: true,
                        placeholder: "",
                        prefix: "",
                        customClass: "",
                        suffix: "",
                        multiple: false,
                        defaultValue: null,
                        protected: false,
                        unique: false,
                        persistent: true,
                        hidden: false,
                        clearOnHide: true,
                        refreshOn: "",
                        redrawOn: "",
                        modalEdit: false,
                        dataGridLabel: false,
                        labelPosition: "top",
                        description: "",
                        errorLabel: "",
                        tooltip: "",
                        hideLabel: false,
                        tabindex: "",
                        disabled: false,
                        autofocus: false,
                        dbIndex: false,
                        customDefaultValue: "",
                        calculateValue: "",
                        calculateServer: false,
                        widget: { type: "input" },
                        attributes: {},
                        validateOn: "change",
                        validate: {
                          required: false,
                          custom: "",
                          customPrivate: false,
                          strictDateValidation: false,
                          multiple: false,
                          unique: false,
                          minLength: "",
                          maxLength: "",
                          pattern: "",
                        },
                        conditional: { show: null, when: null, eq: "" },
                        overlay: {
                          style: "",
                          left: "",
                          top: "",
                          width: "",
                          height: "",
                        },
                        allowCalculateOverride: false,
                        encrypted: false,
                        showCharCount: false,
                        showWordCount: false,
                        properties: {},
                        allowMultipleMasks: false,
                        addons: [],
                        mask: false,
                        inputType: "text",
                        inputFormat: "plain",
                        inputMask: "",
                        displayMask: "",
                        spellcheck: true,
                        truncateMultipleSpaces: false,
                        id: "exybo5i",
                      },
                      {
                        label: "Url",
                        tableView: true,
                        key: "url",
                        type: "textfield",
                        input: true,
                        placeholder: "",
                        prefix: "",
                        customClass: "",
                        suffix: "",
                        multiple: false,
                        defaultValue: null,
                        protected: false,
                        unique: false,
                        persistent: true,
                        hidden: false,
                        clearOnHide: true,
                        refreshOn: "",
                        redrawOn: "",
                        modalEdit: false,
                        dataGridLabel: false,
                        labelPosition: "top",
                        description: "",
                        errorLabel: "",
                        tooltip: "",
                        hideLabel: false,
                        tabindex: "",
                        disabled: false,
                        autofocus: false,
                        dbIndex: false,
                        customDefaultValue: "",
                        calculateValue: "",
                        calculateServer: false,
                        widget: { type: "input" },
                        attributes: {},
                        validateOn: "change",
                        validate: {
                          required: false,
                          custom: "",
                          customPrivate: false,
                          strictDateValidation: false,
                          multiple: false,
                          unique: false,
                          minLength: "",
                          maxLength: "",
                          pattern: "",
                        },
                        conditional: { show: null, when: null, eq: "" },
                        overlay: {
                          style: "",
                          left: "",
                          top: "",
                          width: "",
                          height: "",
                        },
                        allowCalculateOverride: false,
                        encrypted: false,
                        showCharCount: false,
                        showWordCount: false,
                        properties: {},
                        allowMultipleMasks: false,
                        addons: [],
                        mask: false,
                        inputType: "text",
                        inputFormat: "plain",
                        inputMask: "",
                        displayMask: "",
                        spellcheck: true,
                        truncateMultipleSpaces: false,
                        id: "e7g0lpa",
                      },
                      {
                        label: "Icon",
                        autoExpand: false,
                        tableView: true,
                        key: "icon",
                        type: "textarea",
                        input: true,
                        placeholder: "",
                        prefix: "",
                        customClass: "",
                        suffix: "",
                        multiple: false,
                        defaultValue: null,
                        protected: false,
                        unique: false,
                        persistent: true,
                        hidden: false,
                        clearOnHide: true,
                        refreshOn: "",
                        redrawOn: "",
                        modalEdit: false,
                        dataGridLabel: false,
                        labelPosition: "top",
                        description: "",
                        errorLabel: "",
                        tooltip: "",
                        hideLabel: false,
                        tabindex: "",
                        disabled: false,
                        autofocus: false,
                        dbIndex: false,
                        customDefaultValue: "",
                        calculateValue: "",
                        calculateServer: false,
                        widget: { type: "input" },
                        attributes: {},
                        validateOn: "change",
                        validate: {
                          required: false,
                          custom: "",
                          customPrivate: false,
                          strictDateValidation: false,
                          multiple: false,
                          unique: false,
                          minLength: "",
                          maxLength: "",
                          pattern: "",
                          minWords: "",
                          maxWords: "",
                        },
                        conditional: { show: null, when: null, eq: "" },
                        overlay: {
                          style: "",
                          left: "",
                          top: "",
                          width: "",
                          height: "",
                        },
                        allowCalculateOverride: false,
                        encrypted: false,
                        showCharCount: false,
                        showWordCount: false,
                        properties: {},
                        allowMultipleMasks: false,
                        addons: [],
                        mask: false,
                        inputType: "text",
                        inputFormat: "html",
                        inputMask: "",
                        displayMask: "",
                        spellcheck: true,
                        truncateMultipleSpaces: false,
                        rows: 3,
                        wysiwyg: false,
                        editor: "",
                        fixedSize: true,
                        id: "ew12gdd",
                      },
                      {
                        label: "Schema",
                        labelPosition: "top",
                        labelWidth: "",
                        labelMargin: "",
                        description: "",
                        tooltip: "",
                        customClass: "",
                        tabindex: "",
                        openWhenEmpty: false,
                        disableAddingRemovingRows: false,
                        conditionalAddButton: "",
                        hidden: false,
                        hideLabel: false,
                        autofocus: false,
                        disabled: false,
                        tableView: false,
                        modalEdit: false,
                        templates: {
                          header:
                            '<div class="row">\n      {% util.eachComponent(components, function(component) { %}\n        {% if (displayValue(component)) { %}\n          <div class="col-sm-2">{{ t(component.label) }}</div>\n        {% } %}\n      {% }) %}\n    </div>',
                          tableHeader:
                            '\n      <tr>\n        {% util.eachComponent(components, function(component) { %}\n          {% if (!component.hasOwnProperty(\'tableView\') || component.tableView) { %}\n            <td class="editgrid-table-column">{{ component.label }}</td>\n          {% } %}\n        {% }) %}\n        {% if (!instance.options.readOnly && !instance.disabled) { %}\n          <td class="editgrid-table-column">Actions</td>\n        {% } %}\n      </tr>\n    ',
                          row: '<div class="row">\n      {% util.eachComponent(components, function(component) { %}\n        {% if (displayValue(component)) { %}\n          <div class="col-sm-2">\n            {{ isVisibleInRow(component) ? getView(component, row[component.key]) : \'\'}}\n          </div>\n        {% } %}\n      {% }) %}\n      {% if (!instance.options.readOnly && !instance.disabled) { %}\n        <div class="col-sm-2">\n          <div class="btn-group pull-right">\n            <button class="btn btn-default btn-light btn-sm editRow"><i class="{{ iconClass(\'edit\') }}"></i></button>\n            {% if (!instance.hasRemoveButtons || instance.hasRemoveButtons()) { %}\n              <button class="btn btn-danger btn-sm removeRow"><i class="{{ iconClass(\'trash\') }}"></i></button>\n            {% } %}\n          </div>\n        </div>\n      {% } %}\n    </div>',
                          tableRow:
                            '\n      {% util.eachComponent(components, function(component) { %}\n          {% if (!component.hasOwnProperty(\'tableView\') || component.tableView) { %}\n            <td class="editgrid-table-column">\n              {{ getView(component, row[component.key]) }}\n            </td>\n          {% } %}\n        {% }) %}\n        {% if (!instance.options.readOnly && !instance.disabled) { %}\n          <td class="editgrid-table-column">\n            <div class="btn-group">\n              <button class="btn btn-default btn-light btn-sm editRow" aria-label="{{ t(\'Edit row\') }}"><i class="{{ iconClass(\'edit\') }}"></i></button>\n              {% if (!instance.hasRemoveButtons || instance.hasRemoveButtons()) { %}\n              <button class="btn btn-danger btn-sm removeRow" aria-label="{{ t(\'Remove row\') }}"><i class="{{ iconClass(\'trash\') }}"></i></button>\n              {% } %}\n            </div>\n          </td>\n        {% } %}\n    ',
                          footer: "",
                        },
                        rowClass: "",
                        addAnother: "",
                        modal: false,
                        saveRow: "",
                        removeRow: "Cancel",
                        persistent: true,
                        inlineEdit: false,
                        protected: false,
                        dbIndex: false,
                        encrypted: false,
                        redrawOn: "",
                        clearOnHide: true,
                        customDefaultValue: "",
                        calculateValue: "",
                        calculateServer: false,
                        allowCalculateOverride: false,
                        validateOn: "change",
                        validate: {
                          required: false,
                          minLength: "",
                          maxLength: "",
                          customMessage: "",
                          custom: "",
                          customPrivate: false,
                          json: "",
                          strictDateValidation: false,
                          multiple: false,
                          unique: false,
                        },
                        rowDrafts: false,
                        errorLabel: "",
                        errors: "",
                        key: "schema",
                        tags: [],
                        properties: {},
                        conditional: {
                          show: null,
                          when: null,
                          eq: "",
                          json: "",
                        },
                        customConditional: "",
                        logic: [],
                        attributes: {},
                        overlay: {
                          style: "",
                          page: "",
                          left: "",
                          top: "",
                          width: "",
                          height: "",
                        },
                        type: "editgrid",
                        displayAsTable: false,
                        input: true,
                        components: [
                          {
                            collapsible: false,
                            key: "panel1",
                            type: "panel",
                            label: "Panel",
                            input: false,
                            tableView: false,
                            components: [
                              {
                                label: "Name",
                                tableView: true,
                                key: "name",
                                type: "textfield",
                                input: true,
                                placeholder: "",
                                prefix: "",
                                customClass: "",
                                suffix: "",
                                multiple: false,
                                defaultValue: null,
                                protected: false,
                                unique: false,
                                persistent: true,
                                hidden: false,
                                clearOnHide: true,
                                refreshOn: "",
                                redrawOn: "",
                                modalEdit: false,
                                dataGridLabel: false,
                                labelPosition: "top",
                                description: "",
                                errorLabel: "",
                                tooltip: "",
                                hideLabel: false,
                                tabindex: "",
                                disabled: false,
                                autofocus: false,
                                dbIndex: false,
                                customDefaultValue: "",
                                calculateValue: "",
                                calculateServer: false,
                                widget: { type: "input" },
                                attributes: {},
                                validateOn: "change",
                                validate: {
                                  required: false,
                                  custom: "",
                                  customPrivate: false,
                                  strictDateValidation: false,
                                  multiple: false,
                                  unique: false,
                                  minLength: "",
                                  maxLength: "",
                                  pattern: "",
                                },
                                conditional: {
                                  show: null,
                                  when: null,
                                  eq: "",
                                },
                                overlay: {
                                  style: "",
                                  left: "",
                                  top: "",
                                  width: "",
                                  height: "",
                                },
                                allowCalculateOverride: false,
                                encrypted: false,
                                showCharCount: false,
                                showWordCount: false,
                                properties: {},
                                allowMultipleMasks: false,
                                addons: [],
                                mask: false,
                                inputType: "text",
                                inputFormat: "plain",
                                inputMask: "",
                                displayMask: "",
                                spellcheck: true,
                                truncateMultipleSpaces: false,
                                id: "eepi1ue",
                              },
                              {
                                label: "Url",
                                tableView: true,
                                key: "url",
                                type: "textfield",
                                input: true,
                                placeholder: "",
                                prefix: "",
                                customClass: "",
                                suffix: "",
                                multiple: false,
                                defaultValue: null,
                                protected: false,
                                unique: false,
                                persistent: true,
                                hidden: false,
                                clearOnHide: true,
                                refreshOn: "",
                                redrawOn: "",
                                modalEdit: false,
                                dataGridLabel: false,
                                labelPosition: "top",
                                description: "",
                                errorLabel: "",
                                tooltip: "",
                                hideLabel: false,
                                tabindex: "",
                                disabled: false,
                                autofocus: false,
                                dbIndex: false,
                                customDefaultValue: "",
                                calculateValue: "",
                                calculateServer: false,
                                widget: { type: "input" },
                                attributes: {},
                                validateOn: "change",
                                validate: {
                                  required: false,
                                  custom: "",
                                  customPrivate: false,
                                  strictDateValidation: false,
                                  multiple: false,
                                  unique: false,
                                  minLength: "",
                                  maxLength: "",
                                  pattern: "",
                                },
                                conditional: {
                                  show: null,
                                  when: null,
                                  eq: "",
                                },
                                overlay: {
                                  style: "",
                                  left: "",
                                  top: "",
                                  width: "",
                                  height: "",
                                },
                                allowCalculateOverride: false,
                                encrypted: false,
                                showCharCount: false,
                                showWordCount: false,
                                properties: {},
                                allowMultipleMasks: false,
                                addons: [],
                                mask: false,
                                inputType: "text",
                                inputFormat: "plain",
                                inputMask: "",
                                displayMask: "",
                                spellcheck: true,
                                truncateMultipleSpaces: false,
                                id: "ezfqrci",
                              },
                              {
                                label: "Icon",
                                autoExpand: false,
                                tableView: true,
                                key: "icon",
                                type: "textarea",
                                input: true,
                                placeholder: "",
                                prefix: "",
                                customClass: "",
                                suffix: "",
                                multiple: false,
                                defaultValue: null,
                                protected: false,
                                unique: false,
                                persistent: true,
                                hidden: false,
                                clearOnHide: true,
                                refreshOn: "",
                                redrawOn: "",
                                modalEdit: false,
                                dataGridLabel: false,
                                labelPosition: "top",
                                description: "",
                                errorLabel: "",
                                tooltip: "",
                                hideLabel: false,
                                tabindex: "",
                                disabled: false,
                                autofocus: false,
                                dbIndex: false,
                                customDefaultValue: "",
                                calculateValue: "",
                                calculateServer: false,
                                widget: { type: "input" },
                                attributes: {},
                                validateOn: "change",
                                validate: {
                                  required: false,
                                  custom: "",
                                  customPrivate: false,
                                  strictDateValidation: false,
                                  multiple: false,
                                  unique: false,
                                  minLength: "",
                                  maxLength: "",
                                  pattern: "",
                                  minWords: "",
                                  maxWords: "",
                                },
                                conditional: {
                                  show: null,
                                  when: null,
                                  eq: "",
                                },
                                overlay: {
                                  style: "",
                                  left: "",
                                  top: "",
                                  width: "",
                                  height: "",
                                },
                                allowCalculateOverride: false,
                                encrypted: false,
                                showCharCount: false,
                                showWordCount: false,
                                properties: {},
                                allowMultipleMasks: false,
                                addons: [],
                                mask: false,
                                inputType: "text",
                                inputFormat: "html",
                                inputMask: "",
                                displayMask: "",
                                spellcheck: true,
                                truncateMultipleSpaces: false,
                                rows: 3,
                                wysiwyg: false,
                                editor: "",
                                fixedSize: true,
                                id: "eviz5ny",
                              },
                            ],
                            placeholder: "",
                            prefix: "",
                            customClass: "",
                            suffix: "",
                            multiple: false,
                            defaultValue: null,
                            protected: false,
                            unique: false,
                            persistent: false,
                            hidden: false,
                            clearOnHide: false,
                            refreshOn: "",
                            redrawOn: "",
                            modalEdit: false,
                            dataGridLabel: false,
                            labelPosition: "top",
                            description: "",
                            errorLabel: "",
                            tooltip: "",
                            hideLabel: false,
                            tabindex: "",
                            disabled: false,
                            autofocus: false,
                            dbIndex: false,
                            customDefaultValue: "",
                            calculateValue: "",
                            calculateServer: false,
                            widget: null,
                            attributes: {},
                            validateOn: "change",
                            validate: {
                              required: false,
                              custom: "",
                              customPrivate: false,
                              strictDateValidation: false,
                              multiple: false,
                              unique: false,
                            },
                            conditional: { show: null, when: null, eq: "" },
                            overlay: {
                              style: "",
                              left: "",
                              top: "",
                              width: "",
                              height: "",
                            },
                            allowCalculateOverride: false,
                            encrypted: false,
                            showCharCount: false,
                            showWordCount: false,
                            properties: {},
                            allowMultipleMasks: false,
                            addons: [],
                            tree: false,
                            lazyLoad: false,
                            title: "Panel",
                            theme: "default",
                            breadcrumb: "default",
                            id: "et5rrwg",
                          },
                        ],
                        placeholder: "",
                        prefix: "",
                        suffix: "",
                        multiple: false,
                        defaultValue: null,
                        unique: false,
                        refreshOn: "",
                        dataGridLabel: false,
                        widget: null,
                        showCharCount: false,
                        showWordCount: false,
                        allowMultipleMasks: false,
                        addons: [],
                        tree: true,
                        lazyLoad: false,
                        defaultOpen: false,
                        id: "e5rdu2l",
                      },
                    ],
                    placeholder: "",
                    prefix: "",
                    customClass: "",
                    suffix: "",
                    multiple: false,
                    defaultValue: null,
                    protected: false,
                    unique: false,
                    persistent: false,
                    hidden: false,
                    clearOnHide: false,
                    refreshOn: "",
                    redrawOn: "",
                    modalEdit: false,
                    dataGridLabel: false,
                    labelPosition: "top",
                    description: "",
                    errorLabel: "",
                    tooltip: "",
                    hideLabel: false,
                    tabindex: "",
                    disabled: false,
                    autofocus: false,
                    dbIndex: false,
                    customDefaultValue: "",
                    calculateValue: "",
                    calculateServer: false,
                    widget: null,
                    attributes: {},
                    validateOn: "change",
                    validate: {
                      required: false,
                      custom: "",
                      customPrivate: false,
                      strictDateValidation: false,
                      multiple: false,
                      unique: false,
                    },
                    conditional: { show: null, when: null, eq: "" },
                    overlay: {
                      style: "",
                      left: "",
                      top: "",
                      width: "",
                      height: "",
                    },
                    allowCalculateOverride: false,
                    encrypted: false,
                    showCharCount: false,
                    showWordCount: false,
                    properties: {},
                    allowMultipleMasks: false,
                    addons: [],
                    tree: false,
                    lazyLoad: false,
                    title: "Panel",
                    theme: "default",
                    breadcrumb: "default",
                    id: "e632zxf",
                  },
                ],
                placeholder: "",
                prefix: "",
                suffix: "",
                multiple: false,
                defaultValue: null,
                unique: false,
                refreshOn: "",
                dataGridLabel: false,
                widget: null,
                showCharCount: false,
                showWordCount: false,
                allowMultipleMasks: false,
                addons: [],
                tree: true,
                lazyLoad: false,
                defaultOpen: false,
                id: "enn9a3d",
              },
            ],
            id: "ealofhm",
          },
        ],
        display: "form",
      },
    };
  },
};
</script>

<style lang="scss" scoped></style>
